header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'
    - '**/*.thrift'
    - '**/*.proto'

  paths-ignore:
    - '**/kitex_gen/**'
    - 'kitex/**'
    - 'grpc_multi_service/kitex_gen/**'

  comment: on-failure