// Code generated by Kitex v0.9.1. DO NOT EDIT.

package accountservice

import (
	"context"
	"errors"
	account "github.com/cloudwego/kitex-examples/seata_go/kitex_gen/account"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Deduct": kitex.NewMethodInfo(
		deductHandler,
		newAccountServiceDeductArgs,
		newAccountServiceDeductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	accountServiceServiceInfo                = NewServiceInfo()
	accountServiceServiceInfoForClient       = NewServiceInfoForClient()
	accountServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return accountServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return accountServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return accountServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AccountService"
	handlerType := (*account.AccountService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "account",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func deductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*account.AccountServiceDeductArgs)

	err := handler.(account.AccountService).Deduct(ctx, realArg.UserId, realArg.Money)
	if err != nil {
		return err
	}

	return nil
}
func newAccountServiceDeductArgs() interface{} {
	return account.NewAccountServiceDeductArgs()
}

func newAccountServiceDeductResult() interface{} {
	return account.NewAccountServiceDeductResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Deduct(ctx context.Context, userId string, money int32) (err error) {
	var _args account.AccountServiceDeductArgs
	_args.UserId = userId
	_args.Money = money
	var _result account.AccountServiceDeductResult
	if err = p.c.Call(ctx, "Deduct", &_args, &_result); err != nil {
		return
	}
	return nil
}
