// Code generated by Kitex v0.7.3. DO NOT EDIT.
package helloservice

import (
	server "github.com/cloudwego/kitex/server"
	hello "kitex-examples/kitex/protobuf/kitex_gen/hello"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler hello.HelloService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
