name: kitex version tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clear repository
        run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build go image
        run: |
          sh ./go_latest.sh go1.23
        continue-on-error: true

      - name: run on specific version kitex
        run: |
          PWD=$(pwd)
          export GOROOT=$PWD/go1.23
          export PATH=$GOROOT/bin:$PATH
          go version
          ./update_kitex.sh 0bc4a44e9521a73914965c8c3b236e100edd1a95
