name: Push Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check License Header
        uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff

      - name: Lint
        run: |
          test -z "$(gofmt -s -l .)"
          go vet -stdmethods=false $(go list ./...)

      - name: Unit Test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run test.sh
        run: |
          find . -name test.sh -print0 | while IFS= read -r -d '' script; do
            script_dir=$(dirname "$script")
            chmod +x "$script"
            (cd "$script_dir" && bash "./$(basename "$script")")
          done
